name: release
on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
jobs:
  publish_binary:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: release-notes
        run: make release-notes
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v2
        with:
          args: -p 3 release --rm-dist --release-notes=_out/RELEASE_NOTES.md
          version: latest
